#!/usr/bin/env bash
# Create (or rejoin) the fixed dogfood room:
#   codex-arch + grok-impl + claude-impl + codex-impl + claude-rev + codex-rev
# State is written under repo .loom/ (gitignored).
#
# Usage (repo root):
#   bun run dogfood:room          # create if missing, else rejoin all
#   bun run dogfood:room -- --fresh   # always new room
#   bash scripts/dogfood-room-up.sh --fresh
#
# Next session:
#   bun run dogfood:up
#   bun run dogfood:architect   # inside the existing architect/herdr pane
#   # implementation workers: MCP dispatch_card → mac-node → herdr pane
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

STATE_DIR="$ROOT/.loom"
STATE_FILE="$STATE_DIR/dogfood-room.env"
FRESH=0

for arg in "$@"; do
  case "$arg" in
    --fresh|-f) FRESH=1 ;;
    -h|--help)
      sed -n '2,/^set -euo pipefail/{ /^set -euo pipefail/!p; }' "$0" |
        sed 's/^# //' |
        sed 's/^#//'
      exit 0
      ;;
  esac
done

if ! command -v bun >/dev/null 2>&1; then
  echo "error: bun not found on PATH" >&2
  exit 1
fi

loom() {
  bun run packages/cli/src/index.ts "$@"
}

create_room() {
  local create_out
  echo "==> Creating room as codex-arch / codex-architect …"
  create_out="$(loom --profile codex-arch room create --as codex-architect --name "$ROOM_NAME" 2>&1)" || {
    echo "$create_out" >&2
    return 1
  }
  echo "$create_out"
  INVITE="$(echo "$create_out" | grep -Eo 'LOOM-[A-Z0-9]+' | head -1 || true)"
  if [[ -z "$INVITE" ]]; then
    echo "error: could not parse invite code from room create output" >&2
    return 1
  fi
  echo ""
  echo "==> Invite: $INVITE"
}

mkdir -p "$STATE_DIR"

INVITE=""
ROOM_NAME="loom-dev"

if [[ "$FRESH" -eq 0 && -f "$STATE_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$STATE_FILE" || true
  if [[ -n "${LOOM_DOGFOOD_INVITE:-}" ]]; then
    INVITE="$LOOM_DOGFOOD_INVITE"
    ROOM_NAME="${LOOM_DOGFOOD_ROOM_NAME:-loom-dev}"
    echo "Found saved invite: $INVITE (use --fresh for a new room)"
  fi
fi

if [[ -z "$INVITE" || "$FRESH" -eq 1 ]]; then
  create_room
else
  echo "==> Rejoining existing room $INVITE as codex-architect …"
  JOIN_OUT="$(loom --profile codex-arch room join "$INVITE" --as codex-architect 2>&1)" || {
    echo "$JOIN_OUT" >&2
    if [[ "$JOIN_OUT" == *"No room for code"* ]]; then
      echo "warn: saved invite $INVITE is stale; creating a fresh dogfood room" >&2
      INVITE=""
      if ! create_room; then
        exit 1
      fi
      JOIN_OUT=""
    else
      echo "error: codex-arch join failed; saved invite retained" >&2
      exit 1
    fi
  }
  if [[ -n "$JOIN_OUT" && -n "$INVITE" ]]; then
    echo "$JOIN_OUT"
  fi
fi

echo ""
echo "==> Joining grok-impl as grok-impl …"
loom --profile grok-impl room join "$INVITE" --as grok-impl 2>&1

echo ""
echo "==> Joining claude-impl as claude-impl …"
loom --profile claude-impl room join "$INVITE" --as claude-impl 2>&1

echo ""
echo "==> Joining codex-impl as codex-impl …"
loom --profile codex-impl room join "$INVITE" --as codex-impl 2>&1

echo ""
echo "==> Joining claude-rev as claude-review …"
loom --profile claude-rev room join "$INVITE" --as claude-review 2>&1

echo ""
echo "==> Joining codex-rev as codex-review …"
loom --profile codex-rev room join "$INVITE" --as codex-review 2>&1

# Persist for next session (gitignored under .loom/)
{
  echo "# Generated by scripts/dogfood-room-up.sh — do not commit"
  echo "LOOM_DOGFOOD_INVITE=$INVITE"
  echo "LOOM_DOGFOOD_ROOM_NAME=$ROOM_NAME"
  echo "LOOM_DOGFOOD_CREATED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "LOOM_DOGFOOD_ROOT=$ROOT"
} >"$STATE_FILE"

# Human-readable cheat sheet
CHEAT="$STATE_DIR/dogfood-next-session.txt"
cat >"$CHEAT" <<EOF
Loom dogfood room ready
=======================
Invite:  $INVITE
Room:    $ROOM_NAME
State:   $STATE_FILE

Next session (architect pane + bridge-managed worker panes):
-----------------------------------------------------------
# 0) status
cd $ROOT && bun run status && bun run dogfood:status

# A — run this in the existing Codex/herdr architect pane.
# It writes the codex-arch MCP binding with a non-interactive --version call,
# then execs Codex directly. Loom does not remain as a live PTY wrapper.
bun run dogfood:architect
# First prompt: read scripts/dogfood-architect-boot.txt

Architect → Grok default path:
  1. MCP add_task(title=<locked implementation task>, notify=false)
  2. MCP dispatch_card(taskId=<id>, node=mac-node, agentKind=grok,
       prompt=<five-part locked spec + final marker>)
  3. Receive/claim card.done, apply_card_result, then verify pane marker + worktree.

Never start a full-screen worker with 'loom run grok/codex/claude'. Loom relay
events and the agent TUI would write to the same PTY. The bridge owns worker panes.

For corrections/review/ship, create a new explicit card and dispatch the selected
agentKind. dispatch_card performs the doing/mac-node claim transition; do not
pre-claim under grok-impl. codex-arch authors specs and independently verifies.
See docs/DOGFOOD_LOOP.md §1.1. Never mix agent roles in one pane.

Docs: docs/DOGFOOD_LOOP.md
EOF

echo ""
echo "=========================================="
echo " Dogfood room ready"
echo " Invite: $INVITE"
echo " Saved:  $STATE_FILE"
echo " Cheat:  $CHEAT"
echo "=========================================="
echo ""
cat "$CHEAT"
echo ""
echo "Peers (architect view):"
loom --profile codex-arch peers 2>&1 || true
