import type { AgentAdapter, SpawnSpec } from "./types";
import { resolveCommand } from "./which";
import { loomSystemHint } from "./hints";
import {
  buildFableMcpTomlBlock,
  projectMcpSnippetToml,
  upsertUserMcpConfig,
} from "./user-mcp-config";
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

export const codexAdapter: AgentAdapter = {
  id: "codex",
  label: "OpenAI Codex CLI",
  capabilities: {
    mcp: "codex-toml",
    mcpCliFlag: false,
    receive: "both",
    tui: true,
    /** Global ~/.codex/config.toml write is opt-in only (R3 M-3). */
    userConfigWrite: "opt-in",
  },

  async detect() {
    return Boolean(await resolveCommand(["codex"]));
  },

  async spawnSpec(opts): Promise<SpawnSpec> {
    const cmd = (await resolveCommand(["codex"])) ?? "codex";
    return {
      command: cmd,
      args: [...(opts.extraArgs ?? [])],
      env: {
        ...process.env,
        ...opts.env,
        LOOM_ACTIVE: "1",
        LOOM_AGENT: "codex",
        LOOM_MCP_CONFIG: opts.mcpConfigPath,
      },
      cwd: opts.cwd,
    };
  },

  /**
   * Always writes project `.fable/codex.mcp.toml` (with session env).
   * Writes ~/.codex/config.toml only when writeUserConfig is true.
   */
  async ensureMcpConfig(opts) {
    const projectDir = join(opts.cwd, ".loom");
    mkdirSync(projectDir, { recursive: true });
    const snippetPath = join(projectDir, "codex.mcp.toml");
    writeFileSync(
      snippetPath,
      projectMcpSnippetToml({
        header: "# Generated by Fable — Codex MCP (project). Prefer fable run for session binding.",
        mcpStdioPath: opts.mcpStdioPath,
        sessionEnv: opts.sessionEnv,
      }),
      "utf8",
    );

    if (opts.writeUserConfig) {
      const configPath = join(homedir(), ".codex", "config.toml");
      const block = buildFableMcpTomlBlock({
        mcpStdioPath: opts.mcpStdioPath,
        sessionEnv: opts.sessionEnv,
      });
      const r = upsertUserMcpConfig({ configPath, block });
      if (r.written) {
        // surface path for CLI logging via return — project path remains primary
      }
    }

    return snippetPath;
  },

  systemHint() {
    return loomSystemHint("Codex CLI");
  },
};
