import type { AgentAdapter, SpawnSpec } from "./types";
import { resolveCommand } from "./which";
import { loomSystemHint } from "./hints";
import {
  buildFableMcpTomlBlock,
  projectMcpSnippetToml,
  upsertUserMcpConfig,
} from "./user-mcp-config";
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

/**
 * xAI Grok Build TUI (`grok` CLI).
 * MCP: ~/.grok/config.toml [mcp_servers.<name>] — only when writeUserConfig.
 */
export const grokAdapter: AgentAdapter = {
  id: "grok",
  label: "Grok Build",
  capabilities: {
    mcp: "grok-toml",
    mcpCliFlag: false,
    receive: "both",
    tui: true,
    userConfigWrite: "opt-in",
  },

  async detect() {
    return Boolean(await resolveCommand(["grok"]));
  },

  async spawnSpec(opts): Promise<SpawnSpec> {
    const cmd = (await resolveCommand(["grok"])) ?? "grok";
    return {
      command: cmd,
      args: [...(opts.extraArgs ?? [])],
      env: {
        ...process.env,
        ...opts.env,
        LOOM_ACTIVE: "1",
        LOOM_AGENT: "grok",
        LOOM_MCP_CONFIG: opts.mcpConfigPath,
      },
      cwd: opts.cwd,
    };
  },

  async ensureMcpConfig(opts) {
    const projectDir = join(opts.cwd, ".loom");
    mkdirSync(projectDir, { recursive: true });
    const snippetPath = join(projectDir, "grok.mcp.toml");
    writeFileSync(
      snippetPath,
      projectMcpSnippetToml({
        header:
          "# Generated by Fable — Grok MCP (project). Use: fable run grok --write-user-config to install into ~/.grok/config.toml",
        mcpStdioPath: opts.mcpStdioPath,
        sessionEnv: opts.sessionEnv,
        extraServerLines: ["enabled = true"],
      }),
      "utf8",
    );

    if (opts.writeUserConfig) {
      const configPath = join(homedir(), ".grok", "config.toml");
      const block = buildFableMcpTomlBlock({
        mcpStdioPath: opts.mcpStdioPath,
        sessionEnv: opts.sessionEnv,
        extraLines: ["enabled = true"],
      });
      upsertUserMcpConfig({ configPath, block });
    }

    return snippetPath;
  },

  systemHint() {
    return loomSystemHint("Grok Build");
  },
};
